name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-rpm:
    runs-on: ubuntu-latest

    env:
      version: 2.0.1
      pkg: qubes-video-companion

    steps:
    - uses: actions/checkout@v3
    - name: Build fedora docker image
      run: docker build --tag fedora-35-builder --build-arg pkg_name=$pkg-$version .
    - name: Build rpm
      run: docker run -v $PWD/RPMS/:/root/rpmbuild/RPMS/ fedora-35-builder bash -c "rpmbuild -ba /root/rpmbuild/SPECS/$pkg.spec.in"
    - name: Archive packages
      uses: actions/upload-artifact@v3
      with:
        name: rpms
        path: RPMS/
